#*****************************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# system_4x4_vcu108_0.tcl: Tcl script for re-creating project 'tumlis_aramis_demonstrator_system_4x4_vcu108_0'
#
# Generated by Vivado on Sat Jun 10 13:27:13 CEST 2023
# IP Build 2700528 on Thu Nov  7 00:09:20 MST 2019
#
# This file contains the Vivado Tcl commands for re-creating the project to the state*
# when this script was generated. In order to re-create the project, please source this
# file in the Vivado Tcl Shell.
#
# * Note that the runs in the created project will be configured the same way as the
#   original project, however they will not be launched automatically. To regenerate the
#   run results please launch the synthesis/implementation runs as needed.
#
#*****************************************************************************************
# NOTE: In order to use this script for source control purposes, please make sure that the
#       following files are added to the source control system:-
#
# 1. This project restoration tcl script (system_4x4_vcu108_0.tcl) that was generated.
#
# 2. The following source(s) files that were local or imported into the original project.
#    (Please see the '$orig_proj_dir' and '$origin_dir' variable setting below at the start of the script)
#
#    <none>
#
# 3. The following remote source files that were added to the original project:-
#
#    "src/glip_common_channel_0/glip_channel.sv"
#    "src/glip_common_credit_0/verilog/creditor.v"
#    "src/glip_common_credit_0/verilog/debtor.v"
#    "src/glip_common_scaler_0/verilog/glip_downscale.sv"
#    "src/glip_common_scaler_0/verilog/glip_upscale.sv"
#    "src/mor1kx_5.0-r3/rtl/verilog/mor1kx_branch_predictor_gshare.v"
#    "src/mor1kx_5.0-r3/rtl/verilog/mor1kx_branch_predictor_simple.v"
#    "src/mor1kx_5.0-r3/rtl/verilog/mor1kx_branch_predictor_saturation_counter.v"
#    "src/mor1kx_5.0-r3/rtl/verilog/mor1kx_branch_prediction.v"
#    "src/mor1kx_5.0-r3/rtl/verilog/mor1kx_bus_if_wb32.v"
#    "src/mor1kx_5.0-r3/rtl/verilog/mor1kx_cache_lru.v"
#    "src/mor1kx_5.0-r3/rtl/verilog/mor1kx_cfgrs.v"
#    "src/mor1kx_5.0-r3/rtl/verilog/mor1kx_cpu_cappuccino.v"
#    "src/mor1kx_5.0-r3/rtl/verilog/mor1kx_cpu_espresso.v"
#    "src/mor1kx_5.0-r3/rtl/verilog/mor1kx_cpu_prontoespresso.v"
#    "src/mor1kx_5.0-r3/rtl/verilog/mor1kx_cpu.v"
#    "src/mor1kx_5.0-r3/rtl/verilog/mor1kx_ctrl_cappuccino.v"
#    "src/mor1kx_5.0-r3/rtl/verilog/mor1kx_ctrl_espresso.v"
#    "src/mor1kx_5.0-r3/rtl/verilog/mor1kx_ctrl_prontoespresso.v"
#    "src/mor1kx_5.0-r3/rtl/verilog/mor1kx_dcache.v"
#    "src/mor1kx_5.0-r3/rtl/verilog/mor1kx_decode_execute_cappuccino.v"
#    "src/mor1kx_5.0-r3/rtl/verilog/mor1kx_decode.v"
#    "src/mor1kx_5.0-r3/rtl/verilog/mor1kx_dmmu.v"
#    "src/mor1kx_5.0-r3/rtl/verilog/mor1kx_execute_alu.v"
#    "src/mor1kx_5.0-r3/rtl/verilog/mor1kx_execute_ctrl_cappuccino.v"
#    "src/mor1kx_5.0-r3/rtl/verilog/mor1kx_fetch_cappuccino.v"
#    "src/mor1kx_5.0-r3/rtl/verilog/mor1kx_fetch_espresso.v"
#    "src/mor1kx_5.0-r3/rtl/verilog/mor1kx_fetch_prontoespresso.v"
#    "src/mor1kx_5.0-r3/rtl/verilog/mor1kx_fetch_tcm_prontoespresso.v"
#    "src/mor1kx_5.0-r3/rtl/verilog/mor1kx_icache.v"
#    "src/mor1kx_5.0-r3/rtl/verilog/mor1kx_immu.v"
#    "src/mor1kx_5.0-r3/rtl/verilog/mor1kx_lsu_cappuccino.v"
#    "src/mor1kx_5.0-r3/rtl/verilog/mor1kx_lsu_espresso.v"
#    "src/mor1kx_5.0-r3/rtl/verilog/mor1kx_pcu.v"
#    "src/mor1kx_5.0-r3/rtl/verilog/mor1kx_pic.v"
#    "src/mor1kx_5.0-r3/rtl/verilog/mor1kx_rf_cappuccino.v"
#    "src/mor1kx_5.0-r3/rtl/verilog/mor1kx_rf_espresso.v"
#    "src/mor1kx_5.0-r3/rtl/verilog/mor1kx_simple_dpram_sclk.v"
#    "src/mor1kx_5.0-r3/rtl/verilog/mor1kx_store_buffer.v"
#    "src/mor1kx_5.0-r3/rtl/verilog/mor1kx_ticktimer.v"
#    "src/mor1kx_5.0-r3/rtl/verilog/mor1kx_true_dpram_sclk.v"
#    "src/mor1kx_5.0-r3/rtl/verilog/mor1kx.v"
#    "src/mor1kx_5.0-r3/rtl/verilog/mor1kx_wb_mux_cappuccino.v"
#    "src/mor1kx_5.0-r3/rtl/verilog/mor1kx_wb_mux_espresso.v"
#    "src/mor1kx_5.0-r3/rtl/verilog/pfpu32/pfpu32_addsub.v"
#    "src/mor1kx_5.0-r3/rtl/verilog/pfpu32/pfpu32_cmp.v"
#    "src/mor1kx_5.0-r3/rtl/verilog/pfpu32/pfpu32_f2i.v"
#    "src/mor1kx_5.0-r3/rtl/verilog/pfpu32/pfpu32_i2f.v"
#    "src/mor1kx_5.0-r3/rtl/verilog/pfpu32/pfpu32_muldiv.v"
#    "src/mor1kx_5.0-r3/rtl/verilog/pfpu32/pfpu32_rnd.v"
#    "src/mor1kx_5.0-r3/rtl/verilog/pfpu32/pfpu32_top.v"
#    "src/opensocdebug_blocks_tracesample_0/common/osd_tracesample.sv"
#    "src/opensocdebug_interfaces_dii_channel_0/common/dii_channel.sv"
#    "src/opensocdebug_interfaces_dii_channel_0/common/dii_channel_flat.sv"
#    "src/opensocdebug_interfaces_mor1kx_trace_exec_0/or1k/mor1kx_trace_exec.sv"
#    "src/optimsoc_base_constants_0/optimsoc_constants.sv"
#    "src/optimsoc_base_functions_0/optimsoc_functions.sv"
#    "src/optimsoc_bootrom_bootrom_0/verilog/bootrom.v"
#    "src/optimsoc_debug_system_mam_wb_adapter_0/verilog/mam_wb_adapter.sv"
#    "src/optimsoc_fifo_fifo_dualclock_standard_0/verilog/fifo_dualclock_standard.sv"
#    "src/optimsoc_fifo_fifo_singleclock_standard_0/verilog/fifo_singleclock_standard.sv"
#    "src/optimsoc_wb_interconnect_decode_0/verilog/wb_decode.sv"
#    "src/optimsoc_wb_interconnect_mux_0/verilog/wb_mux.sv"
#    "src/optimsoc_wb_interconnect_mux_0/verilog/wb_interconnect_arb_rr.v"
#    "src/tumlis_ft_gs_noc_fault_detection_module_0/verilog/fault_detection_module.sv"
#    "src/tumlis_ft_gs_noc_fault_injection_module_0/verilog/fault_injection_module.sv"
#    "src/tumlis_ft_gs_noc_fifo_singleclock_dual_rd_port_0/verilog/fifo_singleclock_dual_rd_port.sv"
#    "src/tumlis_ft_gs_noc_parity_encoder_module_0/verilog/parity_encoder_module.sv"
#    "src/tumlis_ft_gs_noc_register_stage_0/verilog/register_stage.sv"
#    "src/tumlis_ft_gs_noc_slot_table_ctrl_net_conf_0/verilog/tdm_noc_slot_table.sv"
#    "src/wallento_arbiter_rr_0/arb_rr.sv"
#    "src/wallento_boards_vcu108-fancontrol_0/rtl/verilog/fancontrol.sv"
#    "src/wallento_svchannels_nasti_0/rtl/verilog/nasti_channel.sv"
#    "src/wallento_svchannels_wishbone_0/rtl/verilog/wb_channel.sv"
#    "src/wallento_wb2axi_wb2axi_0/src/wb2axi.sv"
#    "src/opensocdebug_blocks_buffer_0/common/dii_buffer.sv"
#    "src/opensocdebug_blocks_buffer_0/common/osd_fifo.sv"
#    "src/opensocdebug_blocks_eventpacket_0/common/osd_event_packetization.sv"
#    "src/opensocdebug_blocks_timestamp_0/common/osd_timestamp.sv"
#    "src/opensocdebug_interconnect_debug_ring_0/common/debug_ring.sv"
#    "src/opensocdebug_interconnect_debug_ring_0/common/debug_ring_expand.sv"
#    "src/opensocdebug_interconnect_debug_ring_0/common/ring_router_demux.sv"
#    "src/opensocdebug_interconnect_debug_ring_0/common/ring_router.sv"
#    "src/opensocdebug_interconnect_debug_ring_0/common/ring_router_mux.sv"
#    "src/opensocdebug_interconnect_debug_ring_0/common/ring_router_mux_rr.sv"
#    "src/opensocdebug_interconnect_debug_ring_0/common/ring_router_gateway.sv"
#    "src/opensocdebug_interconnect_debug_ring_0/common/ring_router_gateway_demux.sv"
#    "src/opensocdebug_interconnect_debug_ring_0/common/ring_router_gateway_mux.sv"
#    "src/opensocdebug_modules_dem_uart_wb_0/common/osd_dem_uart_wb.sv"
#    "src/opensocdebug_modules_dem_uart_wb_0/common/osd_dem_uart_16550.sv"
#    "src/opensocdebug_modules_dem_uart_wb_0/common/osd_dem_uart.sv"
#    "src/opensocdebug_modules_mam_0/common/osd_mam.sv"
#    "src/optimsoc_base_config_0/optimsoc_config.sv"
#    "src/optimsoc_core_mor1kx_module_0/verilog/mor1kx_module.sv"
#    "src/optimsoc_fifo_fifo_dualclock_fwft_0/verilog/fifo_dualclock_fwft.sv"
#    "src/optimsoc_fifo_fifo_singleclock_fwft_0/verilog/fifo_singleclock_fwft.sv"
#    "src/optimsoc_sram_sp_plain_0/verilog/wb_sram_sp.sv"
#    "src/optimsoc_sram_sp_plain_0/verilog/wb2sram.sv"
#    "src/optimsoc_sram_sp_plain_0/verilog/sram_sp.sv"
#    "src/optimsoc_sram_sp_plain_0/verilog/sram_sp_impl_plain.sv"
#    "src/optimsoc_wb_interconnect_bus_0/verilog/wb_bus_b3.sv"
#    "src/tumlis_aramis_demonstrator_discard_dii_header_0/verilog/discard_header.sv"
#    "src/tumlis_ft_gs_noc_fifo_singleclock_dual_rd_port_fwft_0/verilog/fifo_singleclock_dual_rd_port_fwft.sv"
#    "src/tumlis_ft_gs_noc_fifo_singleclock_dual_rd_port_fwft_0/verilog/fifo_fwft_logic.sv"
#    "src/wallento_boards_vcu108_0/rtl/verilog/vcu108.sv"
#    "src/glip_backend_cypressfx3_0/verilog/glip_cypressfx3_toplevel.sv"
#    "src/glip_backend_uart_0/verilog/glip_uart_control_egress.v"
#    "src/glip_backend_uart_0/verilog/glip_uart_control_ingress.v"
#    "src/glip_backend_uart_0/verilog/glip_uart_control.v"
#    "src/glip_backend_uart_0/verilog/glip_uart_receive.v"
#    "src/glip_backend_uart_0/verilog/glip_uart_toplevel.v"
#    "src/glip_backend_uart_0/verilog/glip_uart_transmit.v"
#    "src/opensocdebug_blocks_eventpacket_fixedwidth_0/common/osd_event_packetization_fixedwidth.sv"
#    "src/opensocdebug_blocks_regaccess_0/common/osd_regaccess.sv"
#    "src/opensocdebug_blocks_regaccess_0/common/osd_regaccess_layer.sv"
#    "src/opensocdebug_blocks_regaccess_0/common/osd_regaccess_demux.sv"
#    "src/opensocdebug_modules_him_0/common/osd_him.sv"
#    "src/opensocdebug_modules_mam_wb_0/wishbone/osd_mam_wb.sv"
#    "src/opensocdebug_modules_mam_wb_0/wishbone/osd_mam_wb_if.sv"
#    "src/optimsoc_noc_buffer_0/verilog/noc_buffer.sv"
#    "src/opensocdebug_modules_ctm_mor1kx_0/or1k/mor1kx/osd_ctm_mor1kx.sv"
#    "src/opensocdebug_modules_ctm_mor1kx_0/common/osd_ctm.sv"
#    "src/opensocdebug_modules_scm_0/common/osd_scm.sv"
#    "src/opensocdebug_modules_stm_mor1kx_0/or1k/mor1kx/osd_stm_mor1kx.sv"
#    "src/opensocdebug_modules_stm_mor1kx_0/common/osd_stm.sv"
#    "src/tumlis_aramis_demonstrator_di_na_bridge_0/verilog/di_na_bridge.sv"
#    "src/tumlis_aramis_demonstrator_di_na_bridge_0/verilog/di_na_bridge_arbiter.sv"
#    "src/tumlis_aramis_demonstrator_di_na_bridge_0/verilog/di_to_noc_flit_buffer.sv"
#    "src/tumlis_aramis_demonstrator_di_na_bridge_0/verilog/gen_wb_write.sv"
#    "src/tumlis_aramis_demonstrator_di_na_bridge_0/verilog/na_read_wb.sv"
#    "src/tumlis_aramis_demonstrator_di_na_bridge_0/verilog/na_write_wb.sv"
#    "src/tumlis_aramis_demonstrator_di_na_bridge_0/verilog/fsm_na_read.sv"
#    "src/tumlis_aramis_demonstrator_di_na_bridge_0/verilog/flit_buffer_32_to_16_bit.sv"
#    "src/tumlis_aramis_demonstrator_di_na_bridge_0/verilog/di_na_bridge_packetizer.sv"
#    "src/tumlis_aramis_demonstrator_noc_control_module_0/verilog/noc_control_module.sv"
#    "src/tumlis_aramis_demonstrator_noc_control_module_0/verilog/noc_control_module_FI.sv"
#    "src/tumlis_aramis_demonstrator_noc_control_module_0/verilog/noc_control_module_FD.sv"
#    "src/tumlis_aramis_demonstrator_noc_control_module_0/verilog/noc_control_module_util_cont.sv"
#    "src/tumlis_aramis_demonstrator_noc_control_module_0/verilog/noc_control_module_util_rec.sv"
#    "src/tumlis_aramis_demonstrator_noc_control_module_0/verilog/noc_control_module_lut_conf.sv"
#    "src/tumlis_aramis_demonstrator_surveillance_module_0/verilog/surveillance_module.sv"
#    "src/tumlis_aramis_demonstrator_surveillance_module_0/verilog/sm_input_decode.sv"
#    "src/tumlis_aramis_demonstrator_surveillance_module_0/verilog/sm_be_send.sv"
#    "src/tumlis_aramis_demonstrator_surveillance_module_0/verilog/sm_be_receive.sv"
#    "src/tumlis_aramis_demonstrator_surveillance_module_0/verilog/sm_tdm_send.sv"
#    "src/tumlis_aramis_demonstrator_surveillance_module_0/verilog/sm_tdm_receive.sv"
#    "src/tumlis_aramis_demonstrator_surveillance_module_0/verilog/sm_collect_event.sv"
#    "src/tumlis_aramis_demonstrator_surveillance_module_0/verilog/sm_config.sv"
#    "src/tumlis_ft_gs_noc_hybrid_noc_ni_0/verilog/hybrid_noc_ni.sv"
#    "src/tumlis_ft_gs_noc_hybrid_noc_ni_0/verilog/ni_slave_decode.sv"
#    "src/tumlis_ft_gs_noc_hybrid_noc_ni_0/verilog/ni_config.sv"
#    "src/tumlis_ft_gs_noc_hybrid_noc_ni_0/verilog/ni_be_channels.sv"
#    "src/tumlis_ft_gs_noc_hybrid_noc_ni_0/verilog/ni_be_endpoint.sv"
#    "src/tumlis_ft_gs_noc_hybrid_noc_ni_0/verilog/ni_tdm_channels.sv"
#    "src/tumlis_ft_gs_noc_hybrid_noc_ni_0/verilog/ni_tdm_endpoint.sv"
#    "src/tumlis_ft_gs_noc_hybrid_noc_ni_0/verilog/ni_tdm_out_queue.sv"
#    "src/tumlis_ft_gs_noc_hybrid_noc_ni_0/verilog/ni_tdm_in_queue.sv"
#    "src/tumlis_ft_gs_noc_hybrid_noc_router_ctrl_net_conf_0/verilog/hybrid_noc_router.sv"
#    "src/tumlis_ft_gs_noc_hybrid_noc_router_ctrl_net_conf_0/verilog/hybrid_noc_router_input.sv"
#    "src/tumlis_ft_gs_noc_hybrid_noc_router_ctrl_net_conf_0/verilog/hybrid_noc_router_lookup_sr.sv"
#    "src/tumlis_ft_gs_noc_hybrid_noc_router_ctrl_net_conf_0/verilog/hybrid_noc_router_lookup_dr.sv"
#    "src/tumlis_ft_gs_noc_hybrid_noc_router_ctrl_net_conf_0/verilog/hybrid_noc_router_output.sv"
#    "src/tumlis_ft_gs_noc_hybrid_noc_router_ctrl_net_conf_0/verilog/hybrid_noc_router_be_arbiter.sv"
#    "src/optimsoc_debug_debug_interface_0/verilog/debug_interface.sv"
#    "src/optimsoc_tile_compute_tile_dm_0/verilog/compute_tile_dm.sv"
#    "src/tumlis_aramis_demonstrator_io_tile_hybrid_0/verilog/io_tile_hybrid.sv"
#    "src/tumlis_aramis_demonstrator_noc_control_module_wrapper_0/verilog/noc_control_module_wrapper.sv"
#    "src/tumlis_ft_gs_noc_hybrid_noc_mesh_ctrl_net_conf_0/verilog/hybrid_noc_mesh.sv"
#    "src/tumlis_aramis_demonstrator_system_4x4_0/verilog/system_4x4.sv"
#    "src/tumlis_aramis_demonstrator_system_4x4_vcu108_0/verilog/system_4x4_vcu108.sv"
#    "src/tumlis_aramis_demonstrator_xilinx_axi_interconnect_16to1_0/ip/xilinx_axi_interconnect_16to1/xilinx_axi_interconnect_16to1.xci"
#    "src/tumlis_aramis_demonstrator_xilinx_axi_register_slice_0/ip/xilinx_axi_register_slice/xilinx_axi_register_slice.xci"
#    "src/wallento_boards_vcu108-axi_clk_converter_0/ip/ddr4_c0_axi_clk_converter/ddr4_c0_axi_clk_converter.xci"
#    "src/wallento_boards_vcu108-ddr_0/ip/mig_ultrascale/mig_ultrascale.xci"
#    "src/wallento_boards_vcu108-system_management_0/ip/system_management/system_management.xci"
#    "src/glip_backend_cypressfx3-vcu108-16bit_0/boards/vcu108/fmc_hpc1.xdc"
#    "src/wallento_boards_vcu108_0/data/pins.xdc"
#
#*****************************************************************************************

# Set the reference directory for source file relative paths (by default the value is script directory path)
set origin_dir "."

# Use origin directory path location variable, if specified in the tcl shell
if { [info exists ::origin_dir_loc] } {
  set origin_dir $::origin_dir_loc
}

# Set the project name
set _xil_proj_name_ "tumlis_aramis_demonstrator_system_4x4_vcu108_0"

# Use project name variable, if specified in the tcl shell
if { [info exists ::user_project_name] } {
  set _xil_proj_name_ $::user_project_name
}

variable script_file
set script_file "system_4x4_vcu108_0.tcl"

# Help information for this script
proc print_help {} {
  variable script_file
  puts "\nDescription:"
  puts "Recreate a Vivado project from this script. The created project will be"
  puts "functionally equivalent to the original project for which this script was"
  puts "generated. The script contains commands for creating a project, filesets,"
  puts "runs, adding/importing sources and setting properties on various objects.\n"
  puts "Syntax:"
  puts "$script_file"
  puts "$script_file -tclargs \[--origin_dir <path>\]"
  puts "$script_file -tclargs \[--project_name <name>\]"
  puts "$script_file -tclargs \[--help\]\n"
  puts "Usage:"
  puts "Name                   Description"
  puts "-------------------------------------------------------------------------"
  puts "\[--origin_dir <path>\]  Determine source file paths wrt this path. Default"
  puts "                       origin_dir path value is \".\", otherwise, the value"
  puts "                       that was set with the \"-paths_relative_to\" switch"
  puts "                       when this script was generated.\n"
  puts "\[--project_name <name>\] Create project with the specified name. Default"
  puts "                       name is the name of the project from where this"
  puts "                       script was generated.\n"
  puts "\[--help\]               Print help information for this script"
  puts "-------------------------------------------------------------------------\n"
  exit 0
}

if { $::argc > 0 } {
  for {set i 0} {$i < $::argc} {incr i} {
    set option [string trim [lindex $::argv $i]]
    switch -regexp -- $option {
      "--origin_dir"   { incr i; set origin_dir [lindex $::argv $i] }
      "--project_name" { incr i; set _xil_proj_name_ [lindex $::argv $i] }
      "--help"         { print_help }
      default {
        if { [regexp {^-} $option] } {
          puts "ERROR: Unknown option '$option' specified, please type '$script_file -tclargs --help' for usage info.\n"
          return 1
        }
      }
    }
  }
}

# Set the directory path for the original project from where this script was exported
set orig_proj_dir "[file normalize "$origin_dir/bld-vivado"]"

# Create project
create_project ${_xil_proj_name_} ./${_xil_proj_name_} -part xcvu095-ffva2104-2-e

# Set the directory path for the new project
set proj_dir [get_property directory [current_project]]

# Set project properties
set obj [current_project]
set_property -name "default_lib" -value "xil_defaultlib" -objects $obj
set_property -name "enable_vhdl_2008" -value "1" -objects $obj
set_property -name "ip_cache_permissions" -value "read write" -objects $obj
set_property -name "ip_output_repo" -value "$proj_dir/${_xil_proj_name_}.cache/ip" -objects $obj
set_property -name "mem.enable_memory_map_generation" -value "1" -objects $obj
set_property -name "part" -value "xcvu095-ffva2104-2-e" -objects $obj
set_property -name "sim.central_dir" -value "$proj_dir/${_xil_proj_name_}.ip_user_files" -objects $obj
set_property -name "sim.ip.auto_export_scripts" -value "1" -objects $obj
set_property -name "simulator_language" -value "Mixed" -objects $obj
set_property -name "source_mgmt_mode" -value "None" -objects $obj
set_property -name "xpm_libraries" -value "XPM_CDC XPM_MEMORY" -objects $obj

# Create 'sources_1' fileset (if not found)
if {[string equal [get_filesets -quiet sources_1] ""]} {
  create_fileset -srcset sources_1
}

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 [file normalize "${origin_dir}/src/glip_common_channel_0/glip_channel.sv"] \
 [file normalize "${origin_dir}/src/glip_common_credit_0/verilog/creditor.v"] \
 [file normalize "${origin_dir}/src/glip_common_credit_0/verilog/debtor.v"] \
 [file normalize "${origin_dir}/src/glip_common_scaler_0/verilog/glip_downscale.sv"] \
 [file normalize "${origin_dir}/src/glip_common_scaler_0/verilog/glip_upscale.sv"] \
 [file normalize "${origin_dir}/src/mor1kx_5.0-r3/rtl/verilog/mor1kx_branch_predictor_gshare.v"] \
 [file normalize "${origin_dir}/src/mor1kx_5.0-r3/rtl/verilog/mor1kx_branch_predictor_simple.v"] \
 [file normalize "${origin_dir}/src/mor1kx_5.0-r3/rtl/verilog/mor1kx_branch_predictor_saturation_counter.v"] \
 [file normalize "${origin_dir}/src/mor1kx_5.0-r3/rtl/verilog/mor1kx_branch_prediction.v"] \
 [file normalize "${origin_dir}/src/mor1kx_5.0-r3/rtl/verilog/mor1kx_bus_if_wb32.v"] \
 [file normalize "${origin_dir}/src/mor1kx_5.0-r3/rtl/verilog/mor1kx_cache_lru.v"] \
 [file normalize "${origin_dir}/src/mor1kx_5.0-r3/rtl/verilog/mor1kx_cfgrs.v"] \
 [file normalize "${origin_dir}/src/mor1kx_5.0-r3/rtl/verilog/mor1kx_cpu_cappuccino.v"] \
 [file normalize "${origin_dir}/src/mor1kx_5.0-r3/rtl/verilog/mor1kx_cpu_espresso.v"] \
 [file normalize "${origin_dir}/src/mor1kx_5.0-r3/rtl/verilog/mor1kx_cpu_prontoespresso.v"] \
 [file normalize "${origin_dir}/src/mor1kx_5.0-r3/rtl/verilog/mor1kx_cpu.v"] \
 [file normalize "${origin_dir}/src/mor1kx_5.0-r3/rtl/verilog/mor1kx_ctrl_cappuccino.v"] \
 [file normalize "${origin_dir}/src/mor1kx_5.0-r3/rtl/verilog/mor1kx_ctrl_espresso.v"] \
 [file normalize "${origin_dir}/src/mor1kx_5.0-r3/rtl/verilog/mor1kx_ctrl_prontoespresso.v"] \
 [file normalize "${origin_dir}/src/mor1kx_5.0-r3/rtl/verilog/mor1kx_dcache.v"] \
 [file normalize "${origin_dir}/src/mor1kx_5.0-r3/rtl/verilog/mor1kx_decode_execute_cappuccino.v"] \
 [file normalize "${origin_dir}/src/mor1kx_5.0-r3/rtl/verilog/mor1kx_decode.v"] \
 [file normalize "${origin_dir}/src/mor1kx_5.0-r3/rtl/verilog/mor1kx_dmmu.v"] \
 [file normalize "${origin_dir}/src/mor1kx_5.0-r3/rtl/verilog/mor1kx_execute_alu.v"] \
 [file normalize "${origin_dir}/src/mor1kx_5.0-r3/rtl/verilog/mor1kx_execute_ctrl_cappuccino.v"] \
 [file normalize "${origin_dir}/src/mor1kx_5.0-r3/rtl/verilog/mor1kx_fetch_cappuccino.v"] \
 [file normalize "${origin_dir}/src/mor1kx_5.0-r3/rtl/verilog/mor1kx_fetch_espresso.v"] \
 [file normalize "${origin_dir}/src/mor1kx_5.0-r3/rtl/verilog/mor1kx_fetch_prontoespresso.v"] \
 [file normalize "${origin_dir}/src/mor1kx_5.0-r3/rtl/verilog/mor1kx_fetch_tcm_prontoespresso.v"] \
 [file normalize "${origin_dir}/src/mor1kx_5.0-r3/rtl/verilog/mor1kx_icache.v"] \
 [file normalize "${origin_dir}/src/mor1kx_5.0-r3/rtl/verilog/mor1kx_immu.v"] \
 [file normalize "${origin_dir}/src/mor1kx_5.0-r3/rtl/verilog/mor1kx_lsu_cappuccino.v"] \
 [file normalize "${origin_dir}/src/mor1kx_5.0-r3/rtl/verilog/mor1kx_lsu_espresso.v"] \
 [file normalize "${origin_dir}/src/mor1kx_5.0-r3/rtl/verilog/mor1kx_pcu.v"] \
 [file normalize "${origin_dir}/src/mor1kx_5.0-r3/rtl/verilog/mor1kx_pic.v"] \
 [file normalize "${origin_dir}/src/mor1kx_5.0-r3/rtl/verilog/mor1kx_rf_cappuccino.v"] \
 [file normalize "${origin_dir}/src/mor1kx_5.0-r3/rtl/verilog/mor1kx_rf_espresso.v"] \
 [file normalize "${origin_dir}/src/mor1kx_5.0-r3/rtl/verilog/mor1kx_simple_dpram_sclk.v"] \
 [file normalize "${origin_dir}/src/mor1kx_5.0-r3/rtl/verilog/mor1kx_store_buffer.v"] \
 [file normalize "${origin_dir}/src/mor1kx_5.0-r3/rtl/verilog/mor1kx_ticktimer.v"] \
 [file normalize "${origin_dir}/src/mor1kx_5.0-r3/rtl/verilog/mor1kx_true_dpram_sclk.v"] \
 [file normalize "${origin_dir}/src/mor1kx_5.0-r3/rtl/verilog/mor1kx.v"] \
 [file normalize "${origin_dir}/src/mor1kx_5.0-r3/rtl/verilog/mor1kx_wb_mux_cappuccino.v"] \
 [file normalize "${origin_dir}/src/mor1kx_5.0-r3/rtl/verilog/mor1kx_wb_mux_espresso.v"] \
 [file normalize "${origin_dir}/src/mor1kx_5.0-r3/rtl/verilog/pfpu32/pfpu32_addsub.v"] \
 [file normalize "${origin_dir}/src/mor1kx_5.0-r3/rtl/verilog/pfpu32/pfpu32_cmp.v"] \
 [file normalize "${origin_dir}/src/mor1kx_5.0-r3/rtl/verilog/pfpu32/pfpu32_f2i.v"] \
 [file normalize "${origin_dir}/src/mor1kx_5.0-r3/rtl/verilog/pfpu32/pfpu32_i2f.v"] \
 [file normalize "${origin_dir}/src/mor1kx_5.0-r3/rtl/verilog/pfpu32/pfpu32_muldiv.v"] \
 [file normalize "${origin_dir}/src/mor1kx_5.0-r3/rtl/verilog/pfpu32/pfpu32_rnd.v"] \
 [file normalize "${origin_dir}/src/mor1kx_5.0-r3/rtl/verilog/pfpu32/pfpu32_top.v"] \
 [file normalize "${origin_dir}/src/opensocdebug_blocks_tracesample_0/common/osd_tracesample.sv"] \
 [file normalize "${origin_dir}/src/opensocdebug_interfaces_dii_channel_0/common/dii_channel.sv"] \
 [file normalize "${origin_dir}/src/opensocdebug_interfaces_dii_channel_0/common/dii_channel_flat.sv"] \
 [file normalize "${origin_dir}/src/opensocdebug_interfaces_mor1kx_trace_exec_0/or1k/mor1kx_trace_exec.sv"] \
 [file normalize "${origin_dir}/src/optimsoc_base_constants_0/optimsoc_constants.sv"] \
 [file normalize "${origin_dir}/src/optimsoc_base_functions_0/optimsoc_functions.sv"] \
 [file normalize "${origin_dir}/src/optimsoc_bootrom_bootrom_0/verilog/bootrom.v"] \
 [file normalize "${origin_dir}/src/optimsoc_debug_system_mam_wb_adapter_0/verilog/mam_wb_adapter.sv"] \
 [file normalize "${origin_dir}/src/optimsoc_fifo_fifo_dualclock_standard_0/verilog/fifo_dualclock_standard.sv"] \
 [file normalize "${origin_dir}/src/optimsoc_fifo_fifo_singleclock_standard_0/verilog/fifo_singleclock_standard.sv"] \
 [file normalize "${origin_dir}/src/optimsoc_wb_interconnect_decode_0/verilog/wb_decode.sv"] \
 [file normalize "${origin_dir}/src/optimsoc_wb_interconnect_mux_0/verilog/wb_mux.sv"] \
 [file normalize "${origin_dir}/src/optimsoc_wb_interconnect_mux_0/verilog/wb_interconnect_arb_rr.v"] \
 [file normalize "${origin_dir}/src/tumlis_ft_gs_noc_fault_detection_module_0/verilog/fault_detection_module.sv"] \
 [file normalize "${origin_dir}/src/tumlis_ft_gs_noc_fault_injection_module_0/verilog/fault_injection_module.sv"] \
 [file normalize "${origin_dir}/src/tumlis_ft_gs_noc_fifo_singleclock_dual_rd_port_0/verilog/fifo_singleclock_dual_rd_port.sv"] \
 [file normalize "${origin_dir}/src/tumlis_ft_gs_noc_parity_encoder_module_0/verilog/parity_encoder_module.sv"] \
 [file normalize "${origin_dir}/src/tumlis_ft_gs_noc_register_stage_0/verilog/register_stage.sv"] \
 [file normalize "${origin_dir}/src/tumlis_ft_gs_noc_slot_table_ctrl_net_conf_0/verilog/tdm_noc_slot_table.sv"] \
 [file normalize "${origin_dir}/src/wallento_arbiter_rr_0/arb_rr.sv"] \
 [file normalize "${origin_dir}/src/wallento_boards_vcu108-fancontrol_0/rtl/verilog/fancontrol.sv"] \
 [file normalize "${origin_dir}/src/wallento_svchannels_nasti_0/rtl/verilog/nasti_channel.sv"] \
 [file normalize "${origin_dir}/src/wallento_svchannels_wishbone_0/rtl/verilog/wb_channel.sv"] \
 [file normalize "${origin_dir}/src/wallento_wb2axi_wb2axi_0/src/wb2axi.sv"] \
 [file normalize "${origin_dir}/src/opensocdebug_blocks_buffer_0/common/dii_buffer.sv"] \
 [file normalize "${origin_dir}/src/opensocdebug_blocks_buffer_0/common/osd_fifo.sv"] \
 [file normalize "${origin_dir}/src/opensocdebug_blocks_eventpacket_0/common/osd_event_packetization.sv"] \
 [file normalize "${origin_dir}/src/opensocdebug_blocks_timestamp_0/common/osd_timestamp.sv"] \
 [file normalize "${origin_dir}/src/opensocdebug_interconnect_debug_ring_0/common/debug_ring.sv"] \
 [file normalize "${origin_dir}/src/opensocdebug_interconnect_debug_ring_0/common/debug_ring_expand.sv"] \
 [file normalize "${origin_dir}/src/opensocdebug_interconnect_debug_ring_0/common/ring_router_demux.sv"] \
 [file normalize "${origin_dir}/src/opensocdebug_interconnect_debug_ring_0/common/ring_router.sv"] \
 [file normalize "${origin_dir}/src/opensocdebug_interconnect_debug_ring_0/common/ring_router_mux.sv"] \
 [file normalize "${origin_dir}/src/opensocdebug_interconnect_debug_ring_0/common/ring_router_mux_rr.sv"] \
 [file normalize "${origin_dir}/src/opensocdebug_interconnect_debug_ring_0/common/ring_router_gateway.sv"] \
 [file normalize "${origin_dir}/src/opensocdebug_interconnect_debug_ring_0/common/ring_router_gateway_demux.sv"] \
 [file normalize "${origin_dir}/src/opensocdebug_interconnect_debug_ring_0/common/ring_router_gateway_mux.sv"] \
 [file normalize "${origin_dir}/src/opensocdebug_modules_dem_uart_wb_0/common/osd_dem_uart_wb.sv"] \
 [file normalize "${origin_dir}/src/opensocdebug_modules_dem_uart_wb_0/common/osd_dem_uart_16550.sv"] \
 [file normalize "${origin_dir}/src/opensocdebug_modules_dem_uart_wb_0/common/osd_dem_uart.sv"] \
 [file normalize "${origin_dir}/src/opensocdebug_modules_mam_0/common/osd_mam.sv"] \
 [file normalize "${origin_dir}/src/optimsoc_base_config_0/optimsoc_config.sv"] \
 [file normalize "${origin_dir}/src/optimsoc_core_mor1kx_module_0/verilog/mor1kx_module.sv"] \
 [file normalize "${origin_dir}/src/optimsoc_fifo_fifo_dualclock_fwft_0/verilog/fifo_dualclock_fwft.sv"] \
 [file normalize "${origin_dir}/src/optimsoc_fifo_fifo_singleclock_fwft_0/verilog/fifo_singleclock_fwft.sv"] \
 [file normalize "${origin_dir}/src/optimsoc_sram_sp_plain_0/verilog/wb_sram_sp.sv"] \
 [file normalize "${origin_dir}/src/optimsoc_sram_sp_plain_0/verilog/wb2sram.sv"] \
 [file normalize "${origin_dir}/src/optimsoc_sram_sp_plain_0/verilog/sram_sp.sv"] \
 [file normalize "${origin_dir}/src/optimsoc_sram_sp_plain_0/verilog/sram_sp_impl_plain.sv"] \
 [file normalize "${origin_dir}/src/optimsoc_wb_interconnect_bus_0/verilog/wb_bus_b3.sv"] \
 [file normalize "${origin_dir}/src/tumlis_aramis_demonstrator_discard_dii_header_0/verilog/discard_header.sv"] \
 [file normalize "${origin_dir}/src/tumlis_ft_gs_noc_fifo_singleclock_dual_rd_port_fwft_0/verilog/fifo_singleclock_dual_rd_port_fwft.sv"] \
 [file normalize "${origin_dir}/src/tumlis_ft_gs_noc_fifo_singleclock_dual_rd_port_fwft_0/verilog/fifo_fwft_logic.sv"] \
 [file normalize "${origin_dir}/src/wallento_boards_vcu108_0/rtl/verilog/vcu108.sv"] \
 [file normalize "${origin_dir}/src/glip_backend_cypressfx3_0/verilog/glip_cypressfx3_toplevel.sv"] \
 [file normalize "${origin_dir}/src/glip_backend_uart_0/verilog/glip_uart_control_egress.v"] \
 [file normalize "${origin_dir}/src/glip_backend_uart_0/verilog/glip_uart_control_ingress.v"] \
 [file normalize "${origin_dir}/src/glip_backend_uart_0/verilog/glip_uart_control.v"] \
 [file normalize "${origin_dir}/src/glip_backend_uart_0/verilog/glip_uart_receive.v"] \
 [file normalize "${origin_dir}/src/glip_backend_uart_0/verilog/glip_uart_toplevel.v"] \
 [file normalize "${origin_dir}/src/glip_backend_uart_0/verilog/glip_uart_transmit.v"] \
 [file normalize "${origin_dir}/src/opensocdebug_blocks_eventpacket_fixedwidth_0/common/osd_event_packetization_fixedwidth.sv"] \
 [file normalize "${origin_dir}/src/opensocdebug_blocks_regaccess_0/common/osd_regaccess.sv"] \
 [file normalize "${origin_dir}/src/opensocdebug_blocks_regaccess_0/common/osd_regaccess_layer.sv"] \
 [file normalize "${origin_dir}/src/opensocdebug_blocks_regaccess_0/common/osd_regaccess_demux.sv"] \
 [file normalize "${origin_dir}/src/opensocdebug_modules_him_0/common/osd_him.sv"] \
 [file normalize "${origin_dir}/src/opensocdebug_modules_mam_wb_0/wishbone/osd_mam_wb.sv"] \
 [file normalize "${origin_dir}/src/opensocdebug_modules_mam_wb_0/wishbone/osd_mam_wb_if.sv"] \
 [file normalize "${origin_dir}/src/optimsoc_noc_buffer_0/verilog/noc_buffer.sv"] \
 [file normalize "${origin_dir}/src/opensocdebug_modules_ctm_mor1kx_0/or1k/mor1kx/osd_ctm_mor1kx.sv"] \
 [file normalize "${origin_dir}/src/opensocdebug_modules_ctm_mor1kx_0/common/osd_ctm.sv"] \
 [file normalize "${origin_dir}/src/opensocdebug_modules_scm_0/common/osd_scm.sv"] \
 [file normalize "${origin_dir}/src/opensocdebug_modules_stm_mor1kx_0/or1k/mor1kx/osd_stm_mor1kx.sv"] \
 [file normalize "${origin_dir}/src/opensocdebug_modules_stm_mor1kx_0/common/osd_stm.sv"] \
 [file normalize "${origin_dir}/src/tumlis_aramis_demonstrator_di_na_bridge_0/verilog/di_na_bridge.sv"] \
 [file normalize "${origin_dir}/src/tumlis_aramis_demonstrator_di_na_bridge_0/verilog/di_na_bridge_arbiter.sv"] \
 [file normalize "${origin_dir}/src/tumlis_aramis_demonstrator_di_na_bridge_0/verilog/di_to_noc_flit_buffer.sv"] \
 [file normalize "${origin_dir}/src/tumlis_aramis_demonstrator_di_na_bridge_0/verilog/gen_wb_write.sv"] \
 [file normalize "${origin_dir}/src/tumlis_aramis_demonstrator_di_na_bridge_0/verilog/na_read_wb.sv"] \
 [file normalize "${origin_dir}/src/tumlis_aramis_demonstrator_di_na_bridge_0/verilog/na_write_wb.sv"] \
 [file normalize "${origin_dir}/src/tumlis_aramis_demonstrator_di_na_bridge_0/verilog/fsm_na_read.sv"] \
 [file normalize "${origin_dir}/src/tumlis_aramis_demonstrator_di_na_bridge_0/verilog/flit_buffer_32_to_16_bit.sv"] \
 [file normalize "${origin_dir}/src/tumlis_aramis_demonstrator_di_na_bridge_0/verilog/di_na_bridge_packetizer.sv"] \
 [file normalize "${origin_dir}/src/tumlis_aramis_demonstrator_noc_control_module_0/verilog/noc_control_module.sv"] \
 [file normalize "${origin_dir}/src/tumlis_aramis_demonstrator_noc_control_module_0/verilog/noc_control_module_FI.sv"] \
 [file normalize "${origin_dir}/src/tumlis_aramis_demonstrator_noc_control_module_0/verilog/noc_control_module_FD.sv"] \
 [file normalize "${origin_dir}/src/tumlis_aramis_demonstrator_noc_control_module_0/verilog/noc_control_module_util_cont.sv"] \
 [file normalize "${origin_dir}/src/tumlis_aramis_demonstrator_noc_control_module_0/verilog/noc_control_module_util_rec.sv"] \
 [file normalize "${origin_dir}/src/tumlis_aramis_demonstrator_noc_control_module_0/verilog/noc_control_module_lut_conf.sv"] \
 [file normalize "${origin_dir}/src/tumlis_aramis_demonstrator_surveillance_module_0/verilog/surveillance_module.sv"] \
 [file normalize "${origin_dir}/src/tumlis_aramis_demonstrator_surveillance_module_0/verilog/sm_input_decode.sv"] \
 [file normalize "${origin_dir}/src/tumlis_aramis_demonstrator_surveillance_module_0/verilog/sm_be_send.sv"] \
 [file normalize "${origin_dir}/src/tumlis_aramis_demonstrator_surveillance_module_0/verilog/sm_be_receive.sv"] \
 [file normalize "${origin_dir}/src/tumlis_aramis_demonstrator_surveillance_module_0/verilog/sm_tdm_send.sv"] \
 [file normalize "${origin_dir}/src/tumlis_aramis_demonstrator_surveillance_module_0/verilog/sm_tdm_receive.sv"] \
 [file normalize "${origin_dir}/src/tumlis_aramis_demonstrator_surveillance_module_0/verilog/sm_collect_event.sv"] \
 [file normalize "${origin_dir}/src/tumlis_aramis_demonstrator_surveillance_module_0/verilog/sm_config.sv"] \
 [file normalize "${origin_dir}/src/tumlis_ft_gs_noc_hybrid_noc_ni_0/verilog/hybrid_noc_ni.sv"] \
 [file normalize "${origin_dir}/src/tumlis_ft_gs_noc_hybrid_noc_ni_0/verilog/ni_slave_decode.sv"] \
 [file normalize "${origin_dir}/src/tumlis_ft_gs_noc_hybrid_noc_ni_0/verilog/ni_config.sv"] \
 [file normalize "${origin_dir}/src/tumlis_ft_gs_noc_hybrid_noc_ni_0/verilog/ni_be_channels.sv"] \
 [file normalize "${origin_dir}/src/tumlis_ft_gs_noc_hybrid_noc_ni_0/verilog/ni_be_endpoint.sv"] \
 [file normalize "${origin_dir}/src/tumlis_ft_gs_noc_hybrid_noc_ni_0/verilog/ni_tdm_channels.sv"] \
 [file normalize "${origin_dir}/src/tumlis_ft_gs_noc_hybrid_noc_ni_0/verilog/ni_tdm_endpoint.sv"] \
 [file normalize "${origin_dir}/src/tumlis_ft_gs_noc_hybrid_noc_ni_0/verilog/ni_tdm_out_queue.sv"] \
 [file normalize "${origin_dir}/src/tumlis_ft_gs_noc_hybrid_noc_ni_0/verilog/ni_tdm_in_queue.sv"] \
 [file normalize "${origin_dir}/src/tumlis_ft_gs_noc_hybrid_noc_router_ctrl_net_conf_0/verilog/hybrid_noc_router.sv"] \
 [file normalize "${origin_dir}/src/tumlis_ft_gs_noc_hybrid_noc_router_ctrl_net_conf_0/verilog/hybrid_noc_router_input.sv"] \
 [file normalize "${origin_dir}/src/tumlis_ft_gs_noc_hybrid_noc_router_ctrl_net_conf_0/verilog/hybrid_noc_router_lookup_sr.sv"] \
 [file normalize "${origin_dir}/src/tumlis_ft_gs_noc_hybrid_noc_router_ctrl_net_conf_0/verilog/hybrid_noc_router_lookup_dr.sv"] \
 [file normalize "${origin_dir}/src/tumlis_ft_gs_noc_hybrid_noc_router_ctrl_net_conf_0/verilog/hybrid_noc_router_output.sv"] \
 [file normalize "${origin_dir}/src/tumlis_ft_gs_noc_hybrid_noc_router_ctrl_net_conf_0/verilog/hybrid_noc_router_be_arbiter.sv"] \
 [file normalize "${origin_dir}/src/optimsoc_debug_debug_interface_0/verilog/debug_interface.sv"] \
 [file normalize "${origin_dir}/src/optimsoc_tile_compute_tile_dm_0/verilog/compute_tile_dm.sv"] \
 [file normalize "${origin_dir}/src/tumlis_aramis_demonstrator_io_tile_hybrid_0/verilog/io_tile_hybrid.sv"] \
 [file normalize "${origin_dir}/src/tumlis_aramis_demonstrator_noc_control_module_wrapper_0/verilog/noc_control_module_wrapper.sv"] \
 [file normalize "${origin_dir}/src/tumlis_ft_gs_noc_hybrid_noc_mesh_ctrl_net_conf_0/verilog/hybrid_noc_mesh.sv"] \
 [file normalize "${origin_dir}/src/tumlis_aramis_demonstrator_system_4x4_0/verilog/system_4x4.sv"] \
 [file normalize "${origin_dir}/src/tumlis_aramis_demonstrator_system_4x4_vcu108_0/verilog/system_4x4_vcu108.sv"] \
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
set file "$origin_dir/src/glip_common_channel_0/glip_channel.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/glip_common_scaler_0/verilog/glip_downscale.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/glip_common_scaler_0/verilog/glip_upscale.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/opensocdebug_blocks_tracesample_0/common/osd_tracesample.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/opensocdebug_interfaces_dii_channel_0/common/dii_channel.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/opensocdebug_interfaces_dii_channel_0/common/dii_channel_flat.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/opensocdebug_interfaces_mor1kx_trace_exec_0/or1k/mor1kx_trace_exec.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/optimsoc_base_constants_0/optimsoc_constants.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/optimsoc_base_functions_0/optimsoc_functions.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/optimsoc_debug_system_mam_wb_adapter_0/verilog/mam_wb_adapter.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/optimsoc_fifo_fifo_dualclock_standard_0/verilog/fifo_dualclock_standard.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/optimsoc_fifo_fifo_singleclock_standard_0/verilog/fifo_singleclock_standard.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/optimsoc_wb_interconnect_decode_0/verilog/wb_decode.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/optimsoc_wb_interconnect_mux_0/verilog/wb_mux.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/optimsoc_wb_interconnect_mux_0/verilog/wb_interconnect_arb_rr.v"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/tumlis_ft_gs_noc_fault_detection_module_0/verilog/fault_detection_module.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/tumlis_ft_gs_noc_fault_injection_module_0/verilog/fault_injection_module.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/tumlis_ft_gs_noc_fifo_singleclock_dual_rd_port_0/verilog/fifo_singleclock_dual_rd_port.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/tumlis_ft_gs_noc_parity_encoder_module_0/verilog/parity_encoder_module.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/tumlis_ft_gs_noc_register_stage_0/verilog/register_stage.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/tumlis_ft_gs_noc_slot_table_ctrl_net_conf_0/verilog/tdm_noc_slot_table.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/wallento_arbiter_rr_0/arb_rr.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/wallento_boards_vcu108-fancontrol_0/rtl/verilog/fancontrol.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/wallento_svchannels_nasti_0/rtl/verilog/nasti_channel.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/wallento_svchannels_wishbone_0/rtl/verilog/wb_channel.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/wallento_wb2axi_wb2axi_0/src/wb2axi.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/opensocdebug_blocks_buffer_0/common/dii_buffer.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/opensocdebug_blocks_buffer_0/common/osd_fifo.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/opensocdebug_blocks_eventpacket_0/common/osd_event_packetization.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/opensocdebug_blocks_timestamp_0/common/osd_timestamp.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/opensocdebug_interconnect_debug_ring_0/common/debug_ring.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/opensocdebug_interconnect_debug_ring_0/common/debug_ring_expand.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/opensocdebug_interconnect_debug_ring_0/common/ring_router_demux.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/opensocdebug_interconnect_debug_ring_0/common/ring_router.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/opensocdebug_interconnect_debug_ring_0/common/ring_router_mux.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/opensocdebug_interconnect_debug_ring_0/common/ring_router_mux_rr.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/opensocdebug_interconnect_debug_ring_0/common/ring_router_gateway.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/opensocdebug_interconnect_debug_ring_0/common/ring_router_gateway_demux.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/opensocdebug_interconnect_debug_ring_0/common/ring_router_gateway_mux.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/opensocdebug_modules_dem_uart_wb_0/common/osd_dem_uart_wb.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/opensocdebug_modules_dem_uart_wb_0/common/osd_dem_uart_16550.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/opensocdebug_modules_dem_uart_wb_0/common/osd_dem_uart.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/opensocdebug_modules_mam_0/common/osd_mam.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/optimsoc_base_config_0/optimsoc_config.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/optimsoc_core_mor1kx_module_0/verilog/mor1kx_module.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/optimsoc_fifo_fifo_dualclock_fwft_0/verilog/fifo_dualclock_fwft.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/optimsoc_fifo_fifo_singleclock_fwft_0/verilog/fifo_singleclock_fwft.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/optimsoc_sram_sp_plain_0/verilog/wb_sram_sp.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/optimsoc_sram_sp_plain_0/verilog/wb2sram.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/optimsoc_sram_sp_plain_0/verilog/sram_sp.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/optimsoc_sram_sp_plain_0/verilog/sram_sp_impl_plain.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/optimsoc_wb_interconnect_bus_0/verilog/wb_bus_b3.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/tumlis_aramis_demonstrator_discard_dii_header_0/verilog/discard_header.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/tumlis_ft_gs_noc_fifo_singleclock_dual_rd_port_fwft_0/verilog/fifo_singleclock_dual_rd_port_fwft.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/tumlis_ft_gs_noc_fifo_singleclock_dual_rd_port_fwft_0/verilog/fifo_fwft_logic.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/wallento_boards_vcu108_0/rtl/verilog/vcu108.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/glip_backend_cypressfx3_0/verilog/glip_cypressfx3_toplevel.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/opensocdebug_blocks_eventpacket_fixedwidth_0/common/osd_event_packetization_fixedwidth.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/opensocdebug_blocks_regaccess_0/common/osd_regaccess.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/opensocdebug_blocks_regaccess_0/common/osd_regaccess_layer.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/opensocdebug_blocks_regaccess_0/common/osd_regaccess_demux.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/opensocdebug_modules_him_0/common/osd_him.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/opensocdebug_modules_mam_wb_0/wishbone/osd_mam_wb.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/opensocdebug_modules_mam_wb_0/wishbone/osd_mam_wb_if.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/optimsoc_noc_buffer_0/verilog/noc_buffer.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/opensocdebug_modules_ctm_mor1kx_0/or1k/mor1kx/osd_ctm_mor1kx.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/opensocdebug_modules_ctm_mor1kx_0/common/osd_ctm.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/opensocdebug_modules_scm_0/common/osd_scm.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/opensocdebug_modules_stm_mor1kx_0/or1k/mor1kx/osd_stm_mor1kx.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/opensocdebug_modules_stm_mor1kx_0/common/osd_stm.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/tumlis_aramis_demonstrator_di_na_bridge_0/verilog/di_na_bridge.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/tumlis_aramis_demonstrator_di_na_bridge_0/verilog/di_na_bridge_arbiter.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/tumlis_aramis_demonstrator_di_na_bridge_0/verilog/di_to_noc_flit_buffer.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/tumlis_aramis_demonstrator_di_na_bridge_0/verilog/gen_wb_write.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/tumlis_aramis_demonstrator_di_na_bridge_0/verilog/na_read_wb.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/tumlis_aramis_demonstrator_di_na_bridge_0/verilog/na_write_wb.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/tumlis_aramis_demonstrator_di_na_bridge_0/verilog/fsm_na_read.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/tumlis_aramis_demonstrator_di_na_bridge_0/verilog/flit_buffer_32_to_16_bit.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/tumlis_aramis_demonstrator_di_na_bridge_0/verilog/di_na_bridge_packetizer.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/tumlis_aramis_demonstrator_noc_control_module_0/verilog/noc_control_module.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/tumlis_aramis_demonstrator_noc_control_module_0/verilog/noc_control_module_FI.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/tumlis_aramis_demonstrator_noc_control_module_0/verilog/noc_control_module_FD.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/tumlis_aramis_demonstrator_noc_control_module_0/verilog/noc_control_module_util_cont.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/tumlis_aramis_demonstrator_noc_control_module_0/verilog/noc_control_module_util_rec.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/tumlis_aramis_demonstrator_noc_control_module_0/verilog/noc_control_module_lut_conf.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/tumlis_aramis_demonstrator_surveillance_module_0/verilog/surveillance_module.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/tumlis_aramis_demonstrator_surveillance_module_0/verilog/sm_input_decode.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/tumlis_aramis_demonstrator_surveillance_module_0/verilog/sm_be_send.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/tumlis_aramis_demonstrator_surveillance_module_0/verilog/sm_be_receive.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/tumlis_aramis_demonstrator_surveillance_module_0/verilog/sm_tdm_send.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/tumlis_aramis_demonstrator_surveillance_module_0/verilog/sm_tdm_receive.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/tumlis_aramis_demonstrator_surveillance_module_0/verilog/sm_collect_event.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/tumlis_aramis_demonstrator_surveillance_module_0/verilog/sm_config.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/tumlis_ft_gs_noc_hybrid_noc_ni_0/verilog/hybrid_noc_ni.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/tumlis_ft_gs_noc_hybrid_noc_ni_0/verilog/ni_slave_decode.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/tumlis_ft_gs_noc_hybrid_noc_ni_0/verilog/ni_config.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/tumlis_ft_gs_noc_hybrid_noc_ni_0/verilog/ni_be_channels.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/tumlis_ft_gs_noc_hybrid_noc_ni_0/verilog/ni_be_endpoint.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/tumlis_ft_gs_noc_hybrid_noc_ni_0/verilog/ni_tdm_channels.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/tumlis_ft_gs_noc_hybrid_noc_ni_0/verilog/ni_tdm_endpoint.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/tumlis_ft_gs_noc_hybrid_noc_ni_0/verilog/ni_tdm_out_queue.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/tumlis_ft_gs_noc_hybrid_noc_ni_0/verilog/ni_tdm_in_queue.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/tumlis_ft_gs_noc_hybrid_noc_router_ctrl_net_conf_0/verilog/hybrid_noc_router.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/tumlis_ft_gs_noc_hybrid_noc_router_ctrl_net_conf_0/verilog/hybrid_noc_router_input.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/tumlis_ft_gs_noc_hybrid_noc_router_ctrl_net_conf_0/verilog/hybrid_noc_router_lookup_sr.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/tumlis_ft_gs_noc_hybrid_noc_router_ctrl_net_conf_0/verilog/hybrid_noc_router_lookup_dr.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/tumlis_ft_gs_noc_hybrid_noc_router_ctrl_net_conf_0/verilog/hybrid_noc_router_output.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/tumlis_ft_gs_noc_hybrid_noc_router_ctrl_net_conf_0/verilog/hybrid_noc_router_be_arbiter.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/optimsoc_debug_debug_interface_0/verilog/debug_interface.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/optimsoc_tile_compute_tile_dm_0/verilog/compute_tile_dm.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/tumlis_aramis_demonstrator_io_tile_hybrid_0/verilog/io_tile_hybrid.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/tumlis_aramis_demonstrator_noc_control_module_wrapper_0/verilog/noc_control_module_wrapper.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/tumlis_ft_gs_noc_hybrid_noc_mesh_ctrl_net_conf_0/verilog/hybrid_noc_mesh.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/tumlis_aramis_demonstrator_system_4x4_0/verilog/system_4x4.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj

set file "$origin_dir/src/tumlis_aramis_demonstrator_system_4x4_vcu108_0/verilog/system_4x4_vcu108.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj


# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset properties
set obj [get_filesets sources_1]
set_property -name "include_dirs" -value "[file normalize "$origin_dir/src/mor1kx_5.0-r3/rtl/verilog"] [file normalize "$origin_dir/src/optimsoc_bootrom_bootrom_0/verilog"] [file normalize "$origin_dir/bld-vivado"]" -objects $obj
set_property -name "top" -value "system_4x4_vcu108" -objects $obj
set_property -name "top_auto_set" -value "0" -objects $obj

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 [file normalize "${origin_dir}/src/tumlis_aramis_demonstrator_xilinx_axi_interconnect_16to1_0/ip/xilinx_axi_interconnect_16to1/xilinx_axi_interconnect_16to1.xci"] \
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
set file "$origin_dir/src/tumlis_aramis_demonstrator_xilinx_axi_interconnect_16to1_0/ip/xilinx_axi_interconnect_16to1/xilinx_axi_interconnect_16to1.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 [file normalize "${origin_dir}/src/tumlis_aramis_demonstrator_xilinx_axi_register_slice_0/ip/xilinx_axi_register_slice/xilinx_axi_register_slice.xci"] \
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
set file "$origin_dir/src/tumlis_aramis_demonstrator_xilinx_axi_register_slice_0/ip/xilinx_axi_register_slice/xilinx_axi_register_slice.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 [file normalize "${origin_dir}/src/wallento_boards_vcu108-axi_clk_converter_0/ip/ddr4_c0_axi_clk_converter/ddr4_c0_axi_clk_converter.xci"] \
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
set file "$origin_dir/src/wallento_boards_vcu108-axi_clk_converter_0/ip/ddr4_c0_axi_clk_converter/ddr4_c0_axi_clk_converter.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 [file normalize "${origin_dir}/src/wallento_boards_vcu108-ddr_0/ip/mig_ultrascale/mig_ultrascale.xci"] \
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
set file "$origin_dir/src/wallento_boards_vcu108-ddr_0/ip/mig_ultrascale/mig_ultrascale.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 [file normalize "${origin_dir}/src/wallento_boards_vcu108-system_management_0/ip/system_management/system_management.xci"] \
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
set file "$origin_dir/src/wallento_boards_vcu108-system_management_0/ip/system_management/system_management.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Set 'sources_1' fileset file properties for local files
# None

# Create 'constrs_1' fileset (if not found)
if {[string equal [get_filesets -quiet constrs_1] ""]} {
  create_fileset -constrset constrs_1
}

# Set 'constrs_1' fileset object
set obj [get_filesets constrs_1]

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/src/glip_backend_cypressfx3-vcu108-16bit_0/boards/vcu108/fmc_hpc1.xdc"]"
set file_added [add_files -norecurse -fileset $obj [list $file]]
set file "$origin_dir/src/glip_backend_cypressfx3-vcu108-16bit_0/boards/vcu108/fmc_hpc1.xdc"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property -name "file_type" -value "XDC" -objects $file_obj

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/src/wallento_boards_vcu108_0/data/pins.xdc"]"
set file_added [add_files -norecurse -fileset $obj [list $file]]
set file "$origin_dir/src/wallento_boards_vcu108_0/data/pins.xdc"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property -name "file_type" -value "XDC" -objects $file_obj

# Set 'constrs_1' fileset properties
set obj [get_filesets constrs_1]
set_property -name "target_part" -value "xcvu095-ffva2104-2-e" -objects $obj

# Create 'sim_1' fileset (if not found)
if {[string equal [get_filesets -quiet sim_1] ""]} {
  create_fileset -simset sim_1
}

# Set 'sim_1' fileset object
set obj [get_filesets sim_1]
# Empty (no sources present)

# Set 'sim_1' fileset properties
set obj [get_filesets sim_1]

# Set 'utils_1' fileset object
set obj [get_filesets utils_1]
# Empty (no sources present)

# Set 'utils_1' fileset properties
set obj [get_filesets utils_1]

# Create 'synth_1' run (if not found)
if {[string equal [get_runs -quiet synth_1] ""]} {
    create_run -name synth_1 -part xcvu095-ffva2104-2-e -flow {Vivado Synthesis 2019} -strategy "Vivado Synthesis Defaults" -report_strategy {No Reports} -constrset constrs_1
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs synth_1]
  set_property flow "Vivado Synthesis 2019" [get_runs synth_1]
}
set obj [get_runs synth_1]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Vivado Synthesis Default Reports} $obj
set_property set_report_strategy_name 0 $obj
# Create 'synth_1_synth_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs synth_1] synth_1_synth_report_utilization_0] "" ] } {
  create_report_config -report_name synth_1_synth_report_utilization_0 -report_type report_utilization:1.0 -steps synth_design -runs synth_1
}
set obj [get_report_configs -of_objects [get_runs synth_1] synth_1_synth_report_utilization_0]
if { $obj != "" } {

}
set obj [get_runs synth_1]
set_property -name "part" -value "xcvu095-ffva2104-2-e" -objects $obj
set_property -name "strategy" -value "Vivado Synthesis Defaults" -objects $obj

# set the current synth run
current_run -synthesis [get_runs synth_1]

# Create 'impl_1' run (if not found)
if {[string equal [get_runs -quiet impl_1] ""]} {
    create_run -name impl_1 -part xcvu095-ffva2104-2-e -flow {Vivado Implementation 2019} -strategy "Vivado Implementation Defaults" -report_strategy {No Reports} -constrset constrs_1 -parent_run synth_1
} else {
  set_property strategy "Vivado Implementation Defaults" [get_runs impl_1]
  set_property flow "Vivado Implementation 2019" [get_runs impl_1]
}
set obj [get_runs impl_1]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Vivado Implementation Default Reports} $obj
set_property set_report_strategy_name 0 $obj
# Create 'impl_1_init_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_init_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_init_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps init_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_init_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj

}
# Create 'impl_1_opt_report_drc_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_drc_0] "" ] } {
  create_report_config -report_name impl_1_opt_report_drc_0 -report_type report_drc:1.0 -steps opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_drc_0]
if { $obj != "" } {

}
# Create 'impl_1_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj

}
# Create 'impl_1_power_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_power_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_power_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps power_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_power_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj

}
# Create 'impl_1_place_report_io_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_io_0] "" ] } {
  create_report_config -report_name impl_1_place_report_io_0 -report_type report_io:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_io_0]
if { $obj != "" } {

}
# Create 'impl_1_place_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_utilization_0] "" ] } {
  create_report_config -report_name impl_1_place_report_utilization_0 -report_type report_utilization:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_utilization_0]
if { $obj != "" } {

}
# Create 'impl_1_place_report_control_sets_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_control_sets_0] "" ] } {
  create_report_config -report_name impl_1_place_report_control_sets_0 -report_type report_control_sets:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_control_sets_0]
if { $obj != "" } {
set_property -name "options.verbose" -value "1" -objects $obj

}
# Create 'impl_1_place_report_incremental_reuse_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_0] "" ] } {
  create_report_config -report_name impl_1_place_report_incremental_reuse_0 -report_type report_incremental_reuse:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_place_report_incremental_reuse_1' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_1] "" ] } {
  create_report_config -report_name impl_1_place_report_incremental_reuse_1 -report_type report_incremental_reuse:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_1]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_place_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_place_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj

}
# Create 'impl_1_post_place_power_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_place_power_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_post_place_power_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps post_place_power_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_place_power_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj

}
# Create 'impl_1_phys_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_phys_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_phys_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_phys_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj

}
# Create 'impl_1_route_report_drc_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_drc_0] "" ] } {
  create_report_config -report_name impl_1_route_report_drc_0 -report_type report_drc:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_drc_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_methodology_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_methodology_0] "" ] } {
  create_report_config -report_name impl_1_route_report_methodology_0 -report_type report_methodology:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_methodology_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_power_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_power_0] "" ] } {
  create_report_config -report_name impl_1_route_report_power_0 -report_type report_power:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_power_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_route_status_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_route_status_0] "" ] } {
  create_report_config -report_name impl_1_route_report_route_status_0 -report_type report_route_status:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_route_status_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_route_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_timing_summary_0]
if { $obj != "" } {
set_property -name "options.max_paths" -value "10" -objects $obj

}
# Create 'impl_1_route_report_incremental_reuse_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_incremental_reuse_0] "" ] } {
  create_report_config -report_name impl_1_route_report_incremental_reuse_0 -report_type report_incremental_reuse:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_incremental_reuse_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_clock_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_clock_utilization_0] "" ] } {
  create_report_config -report_name impl_1_route_report_clock_utilization_0 -report_type report_clock_utilization:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_clock_utilization_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_bus_skew_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_bus_skew_0] "" ] } {
  create_report_config -report_name impl_1_route_report_bus_skew_0 -report_type report_bus_skew:1.1 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_bus_skew_0]
if { $obj != "" } {
set_property -name "options.warn_on_violation" -value "1" -objects $obj

}
# Create 'impl_1_post_route_phys_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_post_route_phys_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps post_route_phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.warn_on_violation" -value "1" -objects $obj

}
# Create 'impl_1_post_route_phys_opt_report_bus_skew_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_bus_skew_0] "" ] } {
  create_report_config -report_name impl_1_post_route_phys_opt_report_bus_skew_0 -report_type report_bus_skew:1.1 -steps post_route_phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_bus_skew_0]
if { $obj != "" } {
set_property -name "options.warn_on_violation" -value "1" -objects $obj

}
set obj [get_runs impl_1]
set_property -name "part" -value "xcvu095-ffva2104-2-e" -objects $obj
set_property -name "strategy" -value "Vivado Implementation Defaults" -objects $obj
set_property -name "steps.phys_opt_design.is_enabled" -value "1" -objects $obj
set_property -name "steps.write_bitstream.args.readback_file" -value "0" -objects $obj
set_property -name "steps.write_bitstream.args.verbose" -value "0" -objects $obj

# set the current impl run
current_run -implementation [get_runs impl_1]

puts "INFO: Project created:${_xil_proj_name_}"
# Create 'drc_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "drc_1" ] ] ""]} {
create_dashboard_gadget -name {drc_1} -type drc
}
set obj [get_dashboard_gadgets [ list "drc_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_drc_0" -objects $obj

# Create 'methodology_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "methodology_1" ] ] ""]} {
create_dashboard_gadget -name {methodology_1} -type methodology
}
set obj [get_dashboard_gadgets [ list "methodology_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_methodology_0" -objects $obj

# Create 'power_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "power_1" ] ] ""]} {
create_dashboard_gadget -name {power_1} -type power
}
set obj [get_dashboard_gadgets [ list "power_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_power_0" -objects $obj

# Create 'timing_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "timing_1" ] ] ""]} {
create_dashboard_gadget -name {timing_1} -type timing
}
set obj [get_dashboard_gadgets [ list "timing_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_timing_summary_0" -objects $obj

# Create 'utilization_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "utilization_1" ] ] ""]} {
create_dashboard_gadget -name {utilization_1} -type utilization
}
set obj [get_dashboard_gadgets [ list "utilization_1" ] ]
set_property -name "reports" -value "synth_1#synth_1_synth_report_utilization_0" -objects $obj
set_property -name "run.step" -value "synth_design" -objects $obj
set_property -name "run.type" -value "synthesis" -objects $obj

# Create 'utilization_2' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "utilization_2" ] ] ""]} {
create_dashboard_gadget -name {utilization_2} -type utilization
}
set obj [get_dashboard_gadgets [ list "utilization_2" ] ]
set_property -name "reports" -value "impl_1#impl_1_place_report_utilization_0" -objects $obj

move_dashboard_gadget -name {utilization_1} -row 0 -col 0
move_dashboard_gadget -name {power_1} -row 1 -col 0
move_dashboard_gadget -name {drc_1} -row 2 -col 0
move_dashboard_gadget -name {timing_1} -row 0 -col 1
move_dashboard_gadget -name {utilization_2} -row 1 -col 1
move_dashboard_gadget -name {methodology_1} -row 2 -col 1
